version: '3.3'

services:
  web:
    image: tifipy/file_storage:master
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
  
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/ 

volumes:
  database-data: