version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn server:app --reload --port 8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env